name: check status

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:

  workflow_run:
    workflows: ["auto tagging branch"]
    types:
      - completed

jobs:

  notify:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run == 'success'
    steps:
      - name: one sample step
        run: |
          echo "state is ${{ github.event.state }} "
          echo "one sample step"
          date
