name: auto tagging branch
on:
  workflow_dispatch:

  pull_request:
    types:
      - closed

jobs:
  settag_if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    name: set new Tag for branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # checkout all history of all branches
      with:
        fetch-depth: 0
    - name: settag
      shell: bash
      run: /bin/bash ci/tag-rebuild_BRANCH.sh ${{ github.base_ref }}
  